# Generated by Django 4.2.16 on 2024-10-21 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nama lengkap beserta gelar')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photo', verbose_name='Foto')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('LAKI-LAKI', 'Laki-laki'), ('PEREMPUAN', 'Perempuan')], max_length=255, null=True, verbose_name='Jenis Kelamin')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kota')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nomor Telepon')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nomor HP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
