# Generated by Django 4.2.16 on 2024-10-23 03:28

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fullname with Salutation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('LAKI-LAKI', 'Laki-laki'), ('PEREMPUAN', 'Perempuan')], max_length=255, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/photo', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Judul Penelitian')),
                ('study_program', models.CharField(max_length=500, verbose_name='Program Studi')),
                ('sample_or_subject', models.CharField(max_length=500, verbose_name='Sample / Subject')),
                ('data', models.CharField(choices=[('PRIMER', 'Primer'), ('SEKUNDER', 'Sekunder')], default='PRIMER', max_length=255, verbose_name='Data Primer/Sekunder')),
                ('submission_file', models.FileField(upload_to='file/submission/', verbose_name='Formulir Pengajuan (Dokumen A)')),
                ('consent_file', models.FileField(upload_to='file/consent/', verbose_name='Informed Consent')),
                ('agreement_file', models.FileField(upload_to='file/agreement/', verbose_name='Lembar Persetujuan')),
                ('institution_letter', models.FileField(upload_to='file/institution_letter/', verbose_name='Surat Pengantar dari Institusi')),
                ('statement_letter', models.FileField(upload_to='file/statement_letter/', verbose_name='Surat Pernyataan penelitian belum dilaksanakan sebelum pengajuan kelaikan etik')),
                ('peer_group_form', models.FileField(upload_to='file/peer_group_form/', verbose_name='Kajian ilmiah oleh peer group atau departemen terkait')),
                ('curriculum_vitae', models.FileField(upload_to='file/curriculum_vitae/', verbose_name='Biodata peneliti tentang penelitian yang telah dilaksanakan')),
                ('payment', models.FileField(upload_to='file/payment/', verbose_name='Bukti Pembayaran')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title')),
                ('status', models.CharField(choices=[('PENGAJUAN SUDAH DITERIMA', 'Pengajuan Sudah Diterima'), ('PENGAJUAN SEDANG DIPROSES', 'Pengajuan sedang diproses'), ('PENGAJUAN SELESAI', 'Pengajuan Selesai')], default='PROSES REVIEW', max_length=255)),
                ('category', models.CharField(blank=True, choices=[('EXEMPTED', 'Exempted'), ('EXPEDITED', 'Expedited'), ('FULLBOARD', 'Fullboard'), ('BELUM DITENTUKAN', 'Belum Ditentukan')], max_length=120, null=True, verbose_name='Kategori Telaah')),
                ('exemption_letter', models.FileField(blank=True, null=True, upload_to='file/exemption_letter', verbose_name='Surat Pembebasan Telaah Etik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Nama Peneliti')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
