# Generated by Django 4.2.16 on 2024-10-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(blank=True, choices=[('EXEMPTED', 'Exempted'), ('EXPEDITED', 'Expedited'), ('FULLBOARD', 'Fullboard'), ('BELUM DITENTUKAN', 'Belum Ditentukan')], default='BELUM DITENTUKAN', max_length=120, null=True, verbose_name='Kategori Telaah'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENGAJUAN SUDAH DITERIMA', 'Pengajuan Sudah Diterima'), ('PENGAJUAN SEDANG DIPROSES', 'Pengajuan sedang diproses'), ('PENGAJUAN SELESAI', 'Pengajuan Selesai')], max_length=255),
        ),
    ]
