# Generated by Django 4.2.16 on 2024-11-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_status_options_alter_status_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.submission'),
        ),
    ]
