# Generated by Django 4.2.16 on 2024-11-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_status_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['created_at']},
        ),
    ]
