# Generated by Django 4.2.16 on 2024-11-03 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_submission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('file_review', models.FileField(blank=True, null=True, upload_to='file/file_review/', verbose_name='Upload hasil review (Dokumen D) ')),
                ('decision', models.CharField(choices=[('DISETUJUI', 'Disetujui'), ('PERBAIKAN MINOR', 'Perbaikan Minor'), ('PERBAIKAN MAYOR', 'Perbaikan Mayor'), ('FULLBOARD', 'FullBoard')], max_length=255, verbose_name='Keputusan')),
                ('review_date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='app.submission')),
            ],
        ),
    ]
