# Generated by Django 4.2.16 on 2024-11-03 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_remove_reviewer_user_reviewer_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewers', related_query_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
