# Generated by Django 4.2.16 on 2024-11-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_reviewer_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewers', related_query_name='reviewer', to='app.profile'),
        ),
    ]
