# Generated by Django 4.2.16 on 2024-11-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_reviewer_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', related_query_name='reviewer', to='app.profile'),
        ),
    ]
