# Generated by Django 4.2.16 on 2024-11-03 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_remove_reviewer_reviewer_reviewer_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', related_query_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
