# Generated by Django 4.2.16 on 2024-11-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_review_review_date_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resubmission_document', models.FileField(upload_to='file/resubmission_document/', verbose_name='Unggah Dokumen Revisi (Dokumen F)')),
                ('review', models.TextField(verbose_name='Hasil Review')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmission', related_query_name='resubmission', to='app.submission')),
            ],
        ),
    ]
