# Generated by Django 4.2.16 on 2024-11-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_resubmission_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', related_query_name='submission', to='app.submission'),
        ),
    ]
