# Generated by Django 4.2.16 on 2024-12-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_resubmission_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amandement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amandement_document', models.FileField(upload_to='file/amandement_document/', verbose_name='Unggah Dokumen Revisi (Dokumen G)')),
                ('review', models.TextField(null=True, verbose_name='Hasil Review')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amandement', related_query_name='amandement', to='app.submission')),
            ],
        ),
    ]
