# Generated by Django 4.2.16 on 2025-02-24 03:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='contain',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Isi Berita'),
        ),
    ]
