# Generated by Django 4.2.16 on 2025-02-24 03:41

import autoslug.fields
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_news_contain_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=150, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='Tidak ada berita', null=True, verbose_name='Isi Berita'),
        ),
    ]
