# Generated by Django 4.2.16 on 2025-02-27 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_news_slug_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hasil Review'),
        ),
    ]
