# Generated by Django 4.2.16 on 2025-02-27 14:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_alter_review_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hasil Review Resubmission')),
                ('file_review', models.FileField(blank=True, null=True, upload_to='file/file_review/', verbose_name='Upload hasil review (Dokumen D) ')),
                ('decision', models.CharField(choices=[('DISETUJUI', 'Disetujui'), ('PERBAIKAN MINOR', 'Perbaikan Minor'), ('PERBAIKAN MAYOR', 'Perbaikan Mayor'), ('FULLBOARD', 'FullBoard')], max_length=255, verbose_name='Keputusan')),
                ('review_date', models.DateField(verbose_name='Tanggal Selesai Review')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('resubmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_resubmission', related_query_name='review_resubmission', to='app.resubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_resubmission', related_query_name='review_resubmission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
