# Generated by Django 4.2.16 on 2025-02-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_reviewresubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewresubmission',
            name='resubmission',
        ),
        migrations.AddField(
            model_name='reviewresubmission',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_resubmission', related_query_name='review_resubmission', to='app.submission'),
        ),
    ]
